IDPT-355: Extend Account Module to Add Roles
ONSdigital/terraform-aws-account pull request #5
Opened 2021-03-26 15:45 UTC by djsd123

[Jira Ticket](https://collaborate2.ons.gov.uk/jira/browse/IDPT-355)

Refactor Module:
- removed provider blocks.  Should be implemented outside of module
  - one was to configure region
  - the other was used to associate the created account with an organisation
- split resources into different terraform files depending on type
- modified resource names
- added the roles and policies for restricted-admin, restricted-admin-read-only, developer, developer-read-only and end-user
- added contract tests to variables
- added unit tests for dev AWS account role, policy logic
- added unit tests for s3 splunk logs logic
- pinned versions to terraform 14 and aws provider ~> 3
- amended readme to reflect changes
- added steps to github actions yaml

2021-03-26 15:57 UTC, benjaminsherwood requested changes

2021-03-26 15:57 UTC, benjaminsherwood commented on README.md
> +To provision an AWS account for development purposes, pass the value `dev` to the `aacount_env` argument.
Typo - aacount_env

2021-03-26 17:53 UTC, benjaminsherwood approved these changes

2021-03-29 07:57 UTC, djsd123 commented
Cheers @benjaminsherwood

2021-03-29 07:57 UTC, merged